[package]
name = "roguemon"
version = "0.1.0"
authors = ["Jeff Lynn <jmlynn@protonmail.com>"]
edition = "2021"

[dependencies]
getrandom = { version = "0.2", features = ["js"] }
bracket-lib = { version = "0.8", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = "0.3"
legion = { version = "0.4", default-features = false, features = [
    "wasm-bindgen",
    "serialize",
] }
legion_codegen = "0.4"
rand = "0.8"
rand_core = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4"
fixedbitset = { version = "0.4", features = ["serde"] }
euclid = { version = "0.22", features = ["serde"] }
